name: Run unit tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    name: Lint check
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
      - run: pod lib lint
      - run: swiftlint --strict

  test_on_macOS:
    name: Build and Test on macOS
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -s /Applications/Xcode_15.4.app
      - run: swift --version
      - run: swift test

  test_Linux:
    name: Build and Test on Linux
    strategy:
      matrix:
        swift-version: ["5.10"]
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup swiftenv
        run: |
          git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
          export SWIFTENV_ROOT="$HOME/.swiftenv"
          export PATH="$SWIFTENV_ROOT/bin:$PATH"
          eval "$(swiftenv init -)"
          echo "$PATH" >> $GITHUB_PATH
      - run: rm .swift-version
      - name: Install Swift
        run: swiftenv install "${{ matrix.swift-version }}" --skip-existing
      - run: swift --version
      - run: swift test --enable-test-discovery
